<?php

namespace app\services;

use app\modules\product\models\Product;
use keltstr\simplehtmldom\SimpleHTMLDom;
use yii\base\Component;
use yii\httpclient\Client;

class ParseService extends Component
{
//    const DEFAULT_URL = 'https://www.srubimbanu.ru/proekty-ban/access_token?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';
    const DEFAULT_URL = 'www.srubimbanu.ru/proekty-ban';
    public $lastResponse;
    public $client;
    public $lastRequest;

    public function __construct($config = [])
    {
        $this->client = $client = new Client([
            'transport' => 'yii\httpclient\CurlTransport',
            'baseUrl' => self::DEFAULT_URL,
        ]);
//        $this->init();
        parent::__construct($config);
    }

//    public function init()
//    {
//        $this->client = $client = new Client([
//            'transport' => 'yii\httpclient\CurlTransport',
//            'baseUrl' => self::DEFAULT_URL,
//        ]);
//        parent::init(); // TODO: Change the autogenerated stub
//    }

    public function parseProducts($url = self::DEFAULT_URL)
    {
        try {

//            $response = $this->client->createRequest()
//                ->setMethod('GET')
//                ->setUrl('https://www.srubimbanu.ru/proekty-ban/gotovye-proekty/' .  http_build_query([
//                        'access_token' => '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',
//                    ]))
//                ->send();

            $request = $this->client->get($url);
            $this->lastResponse = $request->send();

            $page = SimpleHTMLDom::str_get_html($this->lastResponse->content);
            var_dump($page->find('text'));die();
            foreach ($page->find('.catalogbox__item') as $product){

                var_dump($product->find('catalogbox__img'));die();
            }
        } catch (\Exception $e) {
            echo $e->getMessage() . ' ' . $e->getCode() . ' ' . $e->getLine() . ' ' . $e->getFile();
        }
    }
}