#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use Cekurte\Environment\Environment;
use Symfony\Component\Dotenv\Dotenv;

require __DIR__ . '/vendor/autoload.php';

if (file_exists(__DIR__.'/.env')) {
    $dotenv = new Dotenv();
    $dotenv->load(__DIR__.'/.env');
}

defined('YII_DEBUG') or define('YII_DEBUG', Environment::get('YII_DEBUG'));
defined('YII_ENV') or define('YII_ENV', Environment::get('YII_ENV'));

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
